# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=100)),
                ('long_url', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2017, 7, 24, 17, 36, 49, 485522))),
            ],
        ),
    ]
